spring:
  main:
    allow-circular-references: true
  application:
    name: security with spring-boot 2.0
# OUTPUT
  output:
    ansi:
      enabled: detect
# DATASOURCE
  datasource:
    url: jdbc:h2:file:./em_db
    username: sa
    password:
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        '[format_sql]': true
        '[use_sql_comments]': true
        '[generate_statistics]': false
# JACKSON
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      write-durations-as-timestamps: true
      
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8000
  servlet:
    context-path: /app

logging.file.name: demo.log
logging:
  file:
    max-size: 50MB
    max-history: 10
  level:
    root: info
    '[org.springframework]': info
    '[org.springframework.security]': debug
    '[org.hibernate]': info
    '[org.hibernate.type.descriptor.sql.BasicBinder]': trace
    '[com.mysv986.spring_boot_rest]': debug
