CREATE TABLE IF NOT EXISTS place (
  id BIGINT AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (name)
)
ENGINE = INNODB,
CHARACTER SET = utf8mb4,
COLLATE utf8mb4_general_ci;
